name: Terraform Createresource

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify AWS
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init
        run: terraform init

      - name: Plan
        run: terraform plan

      - name: Apply
        run: terraform apply -auto-approve
