name: Deployment-pipeline

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: self-hosted

    env:
      AWS_REGION: us-east-1
      ACCOUNT_ID: 393060838804
      ECR_REPO: crud-app
      IMAGE_TAG: ${{ github.run_number }}   

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Ensure tools
        run: |
          sudo apt update
          sudo apt install -y curl unzip

          # AWS CLI
          if ! command -v aws &> /dev/null; then
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -o awscliv2.zip
            sudo ./aws/install
          fi

          # kubectl
          if ! command -v kubectl &> /dev/null; then
            curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
          fi

          # helm
          if ! command -v helm &> /dev/null; then
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          fi

      # 🐳 Build (correct path)
      - name: Build Docker image
        run: |
          cd app
          docker build -t $ECR_REPO:$IMAGE_TAG .

      # 🔐 Login
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # 🏷 Tag
      - name: Tag image
        run: |
          docker tag $ECR_REPO:$IMAGE_TAG \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      # 📤 Push
      - name: Push image
        run: |
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      # ☸️ Connect to cluster
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name task-eks-cluster

      # 🚀 Deploy
      - name: Deploy using Helm
        run: |
          helm upgrade --install crud-app ./crud-app \
            --set image.repository=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO \
            --set image.tag=$IMAGE_TAG

      # 🧪 Verify
      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc
